# Generated by Django 5.2.5 on 2025-08-13 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_rename_usersignup_signupregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupregistration',
            old_name='ate_of_birth',
            new_name='date_of_birth',
        ),
    ]
